v3.appId= #
v3.mchId= #
v3.apiKey= #
v3.keyPath= #
v3.certificateType=PKCS12
v3.certificateAlias= #
v3.notifyUri= /api/miniapp/payment/payNotify
v3.refundNotifyUri = /api/miniapp/payment/refundNotify
v3.mockPaymentEnabled = true
